#!/usr/bin/env bash
# Displays "Best School" 10 times using a for loop.

cnt=1
while [ $cnt -le 10 ]
do
	if [ $cnt = 4 ]
	then
		echo "bad luck"
	elif [ $cnt = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((cnt++))
done
